name: soulpot_manager
description: A Flutter project to manage the SoulPot App & Data.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  page_transition: ^2.0.5
  loading_animation_widget: ^1.2.0+1
  cupertino_icons: ^1.0.4
  sidebarx: ^0.4.0
  font_awesome_flutter: ^10.1.0
  google_sign_in_web: ^0.10.1+2
  auth_buttons: ^2.0.4
  http_parser: ^4.0.1
  cloud_firestore_web: ^2.6.16
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Greenhouse
      fonts:
        - asset: assets/fonts/Greenhouse-Regular.otf
          style: normal